/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesElectricityRouteImport } from './routes/services.electricity'
import { Route as ServicesDataRouteImport } from './routes/services.data'
import { Route as ServicesAirtimeRouteImport } from './routes/services.airtime'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesElectricityRoute = ServicesElectricityRouteImport.update({
  id: '/electricity',
  path: '/electricity',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDataRoute = ServicesDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAirtimeRoute = ServicesAirtimeRouteImport.update({
  id: '/airtime',
  path: '/airtime',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/services/airtime': typeof ServicesAirtimeRoute
  '/services/data': typeof ServicesDataRoute
  '/services/electricity': typeof ServicesElectricityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/services/airtime': typeof ServicesAirtimeRoute
  '/services/data': typeof ServicesDataRoute
  '/services/electricity': typeof ServicesElectricityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/services/airtime': typeof ServicesAirtimeRoute
  '/services/data': typeof ServicesDataRoute
  '/services/electricity': typeof ServicesElectricityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/profile'
    | '/register'
    | '/services'
    | '/transactions'
    | '/services/airtime'
    | '/services/data'
    | '/services/electricity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/profile'
    | '/register'
    | '/services'
    | '/transactions'
    | '/services/airtime'
    | '/services/data'
    | '/services/electricity'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/profile'
    | '/register'
    | '/services'
    | '/transactions'
    | '/services/airtime'
    | '/services/data'
    | '/services/electricity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/electricity': {
      id: '/services/electricity'
      path: '/electricity'
      fullPath: '/services/electricity'
      preLoaderRoute: typeof ServicesElectricityRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/data': {
      id: '/services/data'
      path: '/data'
      fullPath: '/services/data'
      preLoaderRoute: typeof ServicesDataRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/airtime': {
      id: '/services/airtime'
      path: '/airtime'
      fullPath: '/services/airtime'
      preLoaderRoute: typeof ServicesAirtimeRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAirtimeRoute: typeof ServicesAirtimeRoute
  ServicesDataRoute: typeof ServicesDataRoute
  ServicesElectricityRoute: typeof ServicesElectricityRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAirtimeRoute: ServicesAirtimeRoute,
  ServicesDataRoute: ServicesDataRoute,
  ServicesElectricityRoute: ServicesElectricityRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
